name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: 101.34.249.158
          username: hsx
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCoK9QRse+8W23+o5PK+CgtrghAggurwJZGZ8y4wt4AkxRuEotJ65VEQR6O3VFebqU8XsvZMBhYjljEHk0nqgGoNiI+ZlhU+Ay+IEnPXTsalXFVzVAmT7MOC35TOHLlc9rlDrC6AiahMuE2uNy5K87XoGgkdZuvBxKEnWsMeLflUePy1wC4nE66iaMI+nNwDjmvRdstd9x5XTX+T38QElCGaqp4oF0JWoj+RDMjtbfrop1OiodQ3CXPk7yHAPau8ZtQRQTVjnjlocCohgNktOQTZvtLB7xJbCsU8yPWBDmDeCEsVm10U6kRJN7N8Q7tRrlyp5BNGV4AcT0yBQpIYaX7bYp9PgMej8L4E5EKztqnB4mOln1SVnNQRaTIRxbT1fdk3ZabACuCh0sKUV/TgNNqhCNJZlpIL78EV6D98g/YMMizmjt570Ysgyt8jT2o9L3n62fewKJ56/5XOSitiizP/zX9/mBmDBveec82k5NLe6LvntR8KGe/VPy+CnQ8Jn8= hsx@VM-4-7-ubuntu
          source: .next
          target: /home/hsx/dawn
